require("thisisamr.packer")
require("thisisamr.remap")
require("thisisamr.telescope")

require("thisisamr.colors")
require("thisisamr.harpoon")
require("thisisamr.undotree")
require("thisisamr.lsp")
require("thisisamr.set")
require("thisisamr.emoji")
require("thisisamr.treesitter")
